image:
  pullPolicy: Always

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

service:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "metrics-server"

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 250Mi

nodeSelector:
  nodegroup: management-arm-rkt-mng

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "management"
    effect: "NoSchedule"
